version: '3'

services:

  apache:
    build: ./docker/php/
    ports:
      - "8889:80"
    expose:
      - 9003
    volumes:
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./src:/var/www/html/web/
