version: '3'

services:

  webserver:
    image: nginx:latest
    ports:
      - "8888:80"
    depends_on:
          - php
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  php:
    build: ./docker/php/
    expose:
      - 9000
      - 9003
    volumes:
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./src:/var/www/html
